#include "../include/SysPulseEngine.hpp"

#include "main.h"   // generated by slint-compiler from ui/main.slint

#include <slint.h>
#include <sstream>
#include <iomanip>
#include <cmath>

namespace {

constexpr int TEST_DURATION_DEFAULT = 30;
constexpr int UPDATE_INTERVAL_MS = 150;

slint::SharedString formatOpsCount(uint64_t ops) {
    std::ostringstream out;
    out << std::fixed << std::setprecision(1);
    if (ops >= 1'000'000'000ULL) {
        out << (ops / 1e9) << "B";
    } else if (ops >= 1'000'000ULL) {
        out << (ops / 1e6) << "M";
    } else if (ops >= 1'000ULL) {
        out << (ops / 1e3) << "K";
    } else {
        out << ops;
    }
    return slint::SharedString(out.str());
}

slint::Color bandwidthColor(double mbPerSec) {
    if (mbPerSec > 20000.0) return slint::Color::from_argb_uint8(255, 0x63, 0x99, 0x22);   // green
    if (mbPerSec > 10000.0) return slint::Color::from_argb_uint8(255, 0xEF, 0x9F, 0x27);   // yellow
    if (mbPerSec > 5000.0)  return slint::Color::from_argb_uint8(255, 0x1D, 0x9E, 0x75);   // cyan
    return slint::Color::from_argb_uint8(255, 0xE2, 0x4B, 0x4A);                            // red
}

} // namespace

class StressTestController {
public:
    StressTestController()
        : engine(TEST_DURATION_DEFAULT),
          window(StressTestWindow::create()) {
        wireCallbacks();
        pushStaticInfo();
    }

    void run() {
        window->run();
    }

private:
    SysPulseEngine engine;
    slint::ComponentHandle<StressTestWindow> window;
    std::unique_ptr<slint::Timer> updateTimer;

    int testDurationSeconds = TEST_DURATION_DEFAULT;
    bool isRunning = false;

    std::vector<float> currentThreadLoads;

    void wireCallbacks() {
        window->on_start_clicked([this] { onStart(); });
        window->on_stop_clicked([this] { onStop(); });
        window->on_duration_changed([this](int seconds) {
            testDurationSeconds = seconds;
        });
        window->on_mode_changed([this](bool isSingleCore) {
            engine.setTestMode(isSingleCore ? CPUStressTest::TestMode::SingleCore : CPUStressTest::TestMode::MultiCore);
        });
    }

    void pushStaticInfo() {
        window->set_is_running(false);
        window->set_elapsed_seconds(0);
        window->set_test_duration_seconds(testDurationSeconds);
        window->set_selected_duration_seconds(testDurationSeconds);
        window->set_core_count(0);
        window->set_hash_ops_display(slint::SharedString("0"));
        window->set_bandwidth_mbps(0.0f);
        window->set_memory_allocated_mb(0);
        window->set_memory_target_mb(0);
        window->set_show_thread_event(false);
        window->set_show_results(false);
        window->set_is_single_core(false);
    }

    void onStart() {
        if (isRunning) return;

        engine.setTestDuration(testDurationSeconds);
        engine.setTestMode(window->get_is_single_core() ? CPUStressTest::TestMode::SingleCore : CPUStressTest::TestMode::MultiCore);
        engine.initialize();

        window->set_core_count(engine.getCoreCount());
        window->set_test_duration_seconds(testDurationSeconds);
        window->set_show_results(false);

        engine.start();

        isRunning = true;
        window->set_is_running(true);

        startUpdateTimer();
    }

    void onStop() {
        if (!isRunning) return;

        engine.stop();

        std::thread cleanup([this] {
            engine.waitForCompletion();
        });
        cleanup.detach();

        isRunning = false;
        window->set_is_running(false);
        window->set_show_thread_event(false);
        if (updateTimer) updateTimer->stop();

        // Populate benchmark results and scores
        BenchmarkResults res = engine.getBenchmarkResults();
        ScoreBreakdown score = engine.getScoreBreakdown();

        std::ostringstream overallOut;
        overallOut << std::fixed << std::setprecision(1) << score.overallScore << " / 10000";
        window->set_overall_score_display(slint::SharedString(overallOut.str()));

        std::ostringstream aluOut, fpuOut, cacheOut, cryptoOut, compOut;
        aluOut << "ALU Score: " << std::fixed << std::setprecision(0) << score.aluScore << " (ALU: " << std::setprecision(1) << res.aluOpsPerSec / 1e6 << " M ops/s)";
        fpuOut << "FPU Score: " << std::fixed << std::setprecision(0) << score.fpuScore << " (FPU: " << std::setprecision(1) << res.fpuOpsPerSec / 1e6 << " M ops/s)";
        cacheOut << "Cache Score: " << std::fixed << std::setprecision(0) << score.cacheScore << " (Latency: " << std::setprecision(2) << res.cacheLatencyNs << " ns)";
        cryptoOut << "Crypto Score: " << std::fixed << std::setprecision(0) << score.cryptoScore << " (Crypto: " << std::setprecision(1) << res.cryptoMbPerSec << " MB/s)";
        compOut << "Compression Score: " << std::fixed << std::setprecision(0) << score.compressionScore << " (Comp: " << std::setprecision(1) << res.compressionMbPerSec << " MB/s)";

        window->set_alu_score_display(slint::SharedString(aluOut.str()));
        window->set_fpu_score_display(slint::SharedString(fpuOut.str()));
        window->set_cache_score_display(slint::SharedString(cacheOut.str()));
        window->set_crypto_score_display(slint::SharedString(cryptoOut.str()));
        window->set_compression_score_display(slint::SharedString(compOut.str()));
        window->set_show_results(true);
    }

    void startUpdateTimer() {
        updateTimer = std::make_unique<slint::Timer>();
        updateTimer->start(
            slint::TimerMode::Repeated,
            std::chrono::milliseconds(UPDATE_INTERVAL_MS),
            [this] { tick(); }
        );
    }

    void tick() {
        double elapsed = engine.getElapsedSeconds();

        if (elapsed >= testDurationSeconds || !engine.shouldContinue()) {
            onStop();
            return;
        }

        window->set_elapsed_seconds(static_cast<int>(elapsed));
        window->set_hash_ops_display(formatOpsCount(engine.getHashOperations()));

        double bandwidth = engine.getMemoryBandwidth();
        window->set_bandwidth_mbps(static_cast<float>(bandwidth));
        window->set_bandwidth_color(bandwidthColor(bandwidth));

        size_t allocatedMb = engine.getMemoryAllocated() / (1024 * 1024);
        size_t targetMb = static_cast<size_t>(
            engine.getTargetMemory() / (1024 * 1024)
        );
        window->set_memory_allocated_mb(static_cast<int>(allocatedMb));
        window->set_memory_target_mb(static_cast<int>(targetMb));

        updateThreadLoads();
    }

    void updateThreadLoads() {
        currentThreadLoads = engine.getThreadLoads();

        auto model = std::make_shared<slint::VectorModel<float>>(currentThreadLoads);
        window->set_thread_loads(model);
    }
};

int main() {
    StressTestController controller;
    controller.run();
    return 0;
}
