#include "../include/CPUStressTest.hpp"
#include "../include/MemoryStressTest.hpp"
#include "../include/TimeManager.hpp"

#include "main.h"   // generated by slint-compiler from ui/main.slint

#include <slint.h>
#include <sstream>
#include <iomanip>
#include <cmath>

namespace {

constexpr int TEST_DURATION_DEFAULT = 30;
constexpr int UPDATE_INTERVAL_MS = 150;

// Formats large op counts the way the console version implies ("4.2M", "812K")
// without pulling formatting logic into the .slint file.
slint::SharedString formatOpsCount(uint64_t ops) {
    std::ostringstream out;
    out << std::fixed << std::setprecision(1);
    if (ops >= 1'000'000'000ULL) {
        out << (ops / 1e9) << "B";
    } else if (ops >= 1'000'000ULL) {
        out << (ops / 1e6) << "M";
    } else if (ops >= 1'000ULL) {
        out << (ops / 1e3) << "K";
    } else {
        out << ops;
    }
    return slint::SharedString(out.str());
}

// Same bandwidth -> color thresholds used in displayBandwidthStatus(),
// just expressed as Slint colors instead of ANSI codes.
slint::Color bandwidthColor(double mbPerSec) {
    if (mbPerSec > 20000.0) return slint::Color::from_argb_uint8(255, 0x63, 0x99, 0x22);   // green
    if (mbPerSec > 10000.0) return slint::Color::from_argb_uint8(255, 0xEF, 0x9F, 0x27);   // yellow
    if (mbPerSec > 5000.0)  return slint::Color::from_argb_uint8(255, 0x1D, 0x9E, 0x75);   // cyan
    return slint::Color::from_argb_uint8(255, 0xE2, 0x4B, 0x4A);                            // red
}

} // namespace

class StressTestController {
public:
    StressTestController()
        : timeManager(TimeManager::getInstance()),
          window(StressTestWindow::create()) {
        wireCallbacks();
        pushStaticInfo();
    }

    void run() {
        window->run();
    }

private:
    TimeManager& timeManager;
    slint::ComponentHandle<StressTestWindow> window;
    std::unique_ptr<slint::Timer> updateTimer;

    CPUStressTest cpuTest;
    MemoryStressTest memoryTest;

    int testDurationSeconds = TEST_DURATION_DEFAULT;
    bool isRunning = false;

    // Per-thread load isn't tracked individually today (CPUStressTest only
    // exposes an aggregate system load). Until that's added, every bar
    // shows the same aggregate value so the panel still grows/shrinks
    // correctly as threads are added or removed. Swap this for real
    // per-thread numbers once CPUStressTest exposes them.
    std::vector<float> currentThreadLoads;

    void wireCallbacks() {
        window->on_start_clicked([this] { onStart(); });
        window->on_stop_clicked([this] { onStop(); });
        window->on_duration_changed([this](int seconds) {
            testDurationSeconds = seconds;
        });
    }

    void pushStaticInfo() {
        window->set_is_running(false);
        window->set_elapsed_seconds(0);
        window->set_test_duration_seconds(testDurationSeconds);
        window->set_selected_duration_seconds(testDurationSeconds);
        window->set_core_count(0);
        window->set_hash_ops_display(slint::SharedString("0"));
        window->set_bandwidth_mbps(0.0f);
        window->set_memory_allocated_mb(0);
        window->set_memory_target_mb(0);
        window->set_show_thread_event(false);
    }

    void onStart() {
        if (isRunning) return;

        cpuTest.initialize();
        memoryTest.initialize();

        window->set_core_count(cpuTest.getCoreCount());
        window->set_test_duration_seconds(testDurationSeconds);

        timeManager.startTimer();
        cpuTest.start();
        memoryTest.start();

        isRunning = true;
        window->set_is_running(true);

        startUpdateTimer();
    }

    void onStop() {
        if (!isRunning) return;

        cpuTest.stop();
        memoryTest.stop();
        timeManager.endTimer();

        // Don't block the UI thread on join(); hand it to a detached
        // worker so waitForCompletion() can finish threads in the
        // background while the window stays responsive.
        std::thread cleanup([this] {
            cpuTest.waitForCompletion();
            memoryTest.waitForCompletion();
        });
        cleanup.detach();

        isRunning = false;
        window->set_is_running(false);
        window->set_show_thread_event(false);
        if (updateTimer) updateTimer->stop();
    }

    void startUpdateTimer() {
        updateTimer = std::make_unique<slint::Timer>();
        updateTimer->start(
            slint::TimerMode::Repeated,
            std::chrono::milliseconds(UPDATE_INTERVAL_MS),
            [this] { tick(); }
        );
    }

    void tick() {
        double elapsed = timeManager.getElapsedSeconds();

        if (elapsed >= testDurationSeconds) {
            onStop();
            return;
        }

        window->set_elapsed_seconds(static_cast<int>(elapsed));
        window->set_hash_ops_display(formatOpsCount(cpuTest.getHashOperations()));

        double bandwidth = memoryTest.getMemoryBandwidth();
        window->set_bandwidth_mbps(static_cast<float>(bandwidth));
        window->set_bandwidth_color(bandwidthColor(bandwidth));

        size_t allocatedMb = memoryTest.getMemoryAllocated() / (1024 * 1024);
        size_t targetMb = static_cast<size_t>(
            (memoryTest.getTargetMemory() + memoryTest.getBandwidthTestSize()) / (1024 * 1024)
        );
        window->set_memory_allocated_mb(static_cast<int>(allocatedMb));
        window->set_memory_target_mb(static_cast<int>(targetMb));

        updateThreadLoads();
    }

    void updateThreadLoads() {
        // One entry per active CPU stress worker (== core count while running),
        // each reflecting genuine per-core utilization from CPU-time sampling.
        currentThreadLoads = cpuTest.getThreadLoads();

        auto model = std::make_shared<slint::VectorModel<float>>(currentThreadLoads);
        window->set_thread_loads(model);
    }
};

int main() {
    StressTestController controller;
    controller.run();
    return 0;
}